DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `postId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY  (`id`)
);
